.TH "scraps/_get_values_from_path.py" 3 "JARVIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scraps/_get_values_from_path.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fB_get_values_from_path\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB_get_values_from_path\&.get_value_from_path\fP (data_dict, path)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JARVIS from the source code\&.
