.TH "_get_values_from_path" 3 "JARVIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_get_values_from_path
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBget_value_from_path\fP (data_dict, path)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "_get_values_from_path\&.get_value_from_path ( data_dict,  path)"

.PP
.nf
Iterates through the keys of a dictionary based on the provided path list\&.

:param data_dict: The dictionary to traverse\&.
:param path: A list of strings representing the path to traverse in the dictionary\&.
:return: The value found at the end of the path, or None if the path is invalid\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for JARVIS from the source code\&.
