.TH "jarvis_utilities" 3 "JARVIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jarvis_utilities
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJarvisUtilitiesMixin\fP"
.br
.RI "Mixin class providing utility functions for the Logger class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JARVIS from the source code\&.
