.TH "jarvis" 3 "JARVIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jarvis
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJARVIS\fP"
.br
.RI "Main class for the \fBJARVIS\fP logging system\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JARVIS from the source code\&.
