.TH "jarvis_printing.JarvisPrintingMixin" 3 "JARVIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jarvis_printing.JarvisPrintingMixin
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcontexts\fP"
.br
.ti -1c
.RI "\fBcurrent_path\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_format_message\fP (self, level, message, name='', ignore=False)"
.br
.ti -1c
.RI "\fB_print\fP (self, name, val='')"
.br
.ti -1c
.RI "\fB_print_contexts\fP (self)"
.br
.ti -1c
.RI "\fB_printIn\fP (self, fn_name)"
.br
.ti -1c
.RI "\fB_printOut\fP (self, fn_name)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "jarvis_printing\&.JarvisPrintingMixin\&._format_message ( self,  level,  message,  name = \fR''\fP,  ignore = \fRFalse\fP)\fR [protected]\fP"

.PP
.nf
Format the log message based on its level\&.

:param level: The logging level\&.
:param message: The message to format\&.
:param name: Optional name to include in the message\&.
:param ignore: Whether to ignore adding the message to the log\&.
:return: The formatted message\&.

.fi
.PP
 
.SS "jarvis_printing\&.JarvisPrintingMixin\&._print ( self,  name,  val = \fR''\fP)\fR [protected]\fP"

.PP
.nf
Print a debug message with the current indentation\&.

:param name: The name of the debug message\&.
:param val: The value or content of the debug message\&.

.fi
.PP
 
.SS "jarvis_printing\&.JarvisPrintingMixin\&._print_contexts ( self)\fR [protected]\fP"

.PP
.nf
Print the current state of contexts for debugging\&.

.fi
.PP
 
.SS "jarvis_printing\&.JarvisPrintingMixin\&._printIn ( self,  fn_name)\fR [protected]\fP"

.PP
.nf
Increase indentation level and print entering message\&.

:param fn_name: The name of the function being entered\&.

.fi
.PP
 
.SS "jarvis_printing\&.JarvisPrintingMixin\&._printOut ( self,  fn_name)\fR [protected]\fP"

.PP
.nf
Decrease indentation level and print exiting message\&.

:param fn_name: The name of the function being exited\&.

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "jarvis_printing\&.JarvisPrintingMixin\&.contexts"

.SS "jarvis_printing\&.JarvisPrintingMixin\&.current_path"


.SH "Author"
.PP 
Generated automatically by Doxygen for JARVIS from the source code\&.
