.TH "JARVIS/jarvis_printing.py" 3 "JARVIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JARVIS/jarvis_printing.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBjarvis_printing\&.JarvisPrintingMixin\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBjarvis_printing\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JARVIS from the source code\&.
