.TH "launch_tests" 3 "JARVIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
launch_tests
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB_importHelp\fP (folder)"
.br
.ti -1c
.RI "\fBimportTests\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtestLib\fP = \fBimportTests\fP()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "launch_tests\&._importHelp ( folder)\fR [protected]\fP"

.PP
.nf
Imports all modules from a specific folder whose names contain 'TEST'\&.

:param folder: The JARVIS/folder you want imported\&.
:return: A dictionary where keys are module names and values are the imported modules\&.

.fi
.PP
 
.SS "launch_tests\&.importTests ()"

.SH "Variable Documentation"
.PP 
.SS "launch_tests\&.testLib = \fBimportTests\fP()"

.SH "Author"
.PP 
Generated automatically by Doxygen for JARVIS from the source code\&.
