.TH "test_helpers.Event" 3 "JARVIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_helpers.Event
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, event_id, \fBhandled\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBhandled\fP = False"
.br
.ti -1c
.RI "\fBid\fP = event_id"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "test_helpers\&.Event\&.__init__ ( self,  event_id,  handled)"

.SH "Member Data Documentation"
.PP 
.SS "bool test_helpers\&.Event\&.handled = False"

.SS "test_helpers\&.Event\&.id = event_id"


.SH "Author"
.PP 
Generated automatically by Doxygen for JARVIS from the source code\&.
