.TH "tests/TEST_GPT_example.py" 3 "JARVIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/TEST_GPT_example.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTEST_GPT_example\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBTEST_GPT_example\&.event1\fP = Event(230, False)"
.br
.ti -1c
.RI "\fBTEST_GPT_example\&.handled\fP"
.br
.ti -1c
.RI "\fBTEST_GPT_example\&.ID_SUP_100\fP"
.br
.ti -1c
.RI "\fBTEST_GPT_example\&.ID_SUP_150\fP"
.br
.ti -1c
.RI "\fBTEST_GPT_example\&.test_handled\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JARVIS from the source code\&.
