.TH "tests/TEST_GPT_custom.py" 3 "JARVIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/TEST_GPT_custom.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTEST_GPT_custom\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBTEST_GPT_custom\&.event1\fP = Event(230, False)"
.br
.ti -1c
.RI "\fBTEST_GPT_custom\&.event2\fP = Event(50, True)"
.br
.ti -1c
.RI "\fBTEST_GPT_custom\&.handled\fP"
.br
.ti -1c
.RI "\fBTEST_GPT_custom\&.test_event_handled\fP"
.br
.ti -1c
.RI "\fBTEST_GPT_custom\&.test_event_id_gt_100\fP"
.br
.ti -1c
.RI "\fBTEST_GPT_custom\&.test_event_id_gt_150\fP"
.br
.ti -1c
.RI "\fBTEST_GPT_custom\&.test_event_id_lt_100\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JARVIS from the source code\&.
