.TH "TEST_GPT_example" 3 "JARVIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TEST_GPT_example
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBevent1\fP = Event(230, False)"
.br
.ti -1c
.RI "\fBhandled\fP"
.br
.ti -1c
.RI "\fBID_SUP_100\fP"
.br
.ti -1c
.RI "\fBID_SUP_150\fP"
.br
.ti -1c
.RI "\fBtest_handled\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "TEST_GPT_example\&.event1 = Event(230, False)"

.SS "TEST_GPT_example\&.handled"

.SS "TEST_GPT_example\&.ID_SUP_100"
\fBInitial value:\fP
.nf
1 =  jarvis\&.AddTest(
2     test_fn=is_more_100["test_fn"],
3     name="Event id >100"
4 )
.PP
.fi

.SS "TEST_GPT_example\&.ID_SUP_150"
\fBInitial value:\fP
.nf
1 =  jarvis\&.AddTest(
2     test_fn=is_more_150["test_fn"],
3     name="Event id >150"
4 )
.PP
.fi

.SS "TEST_GPT_example\&.test_handled"
\fBInitial value:\fP
.nf
1 =  jarvis\&.AddTest(
2     test_fn=lambda x: x,
3     name="Event handled"
4 )
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for JARVIS from the source code\&.
