.TH "tests/test_helpers.py" 3 "JARVIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/test_helpers.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtest_helpers\&.Event\fP"
.br
.RI "Represents a MIDI event\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtest_helpers\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtest_helpers\&.is_more_100\fP"
.br
.ti -1c
.RI "\fBtest_helpers\&.is_more_150\fP"
.br
.ti -1c
.RI "\fBtest_helpers\&.jarvis\fP = JARVIS('INFO')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JARVIS from the source code\&.
